### ISSUE TITLE
The minSdk version is too high in the library

### ISSUE THREAD

**Issue by dymx101** [Mr-Cai/tencent_ad#1]
```
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:tencent_ad] /Users/yiming/Documents/codeMountain/Android Codebase/FDColoringBook/woman_recipe/build/tencent_ad/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="tencent.ad" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 57s
Gradle task assembleDebug failed with exit code 1
```

**Comment by Mr-Cai** [comment]
修复了

**Comment by Mr-Cai** [comment]
> ```
> * What went wrong:
> Execution failed for task ':app:processDebugManifest'.
> > Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:tencent_ad] /Users/yiming/Documents/codeMountain/Android Codebase/FDColoringBook/woman_recipe/build/tencent_ad/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml as the library might be using APIs not available in 16
>   	Suggestion: use a compatible library with a minSdk of at most 16,
>   		or increase this project's minSdk version to at least 19,
>   		or use tools:overrideLibrary="tencent.ad" to force usage (may lead to runtime failures)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 57s
> Gradle task assembleDebug failed with exit code 1
> ```

1.0.1修复了

**Comment by yy1300326388** [comment]
@dymx101 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
