### ISSUE TITLE
Fail to init splash plugin;开屏广告初始化就失败了，是不是漏了什么配置？

### ISSUE THREAD

**Issue by sanyayaya** [Mr-Cai/tencent_ad#10]
I/art     ( 3570): Rejecting re-init on previously-failed class java.lang.Class<com.qq.e.comm.plugin.POFactoryImpl>: java.lang.ExceptionInInitializerError:
I/art     ( 3570): (Throwable with no stack trace)
E/gdt_ad_mob( 3570): Fail to init splash plugin
E/gdt_ad_mob( 3570): com.qq.e.comm.managers.plugin.c: Fail to getfactory implement instance for interface:com.qq.e.comm.pi.POFactory
E/gdt_ad_mob( 3570): 	at com.qq.e.comm.managers.plugin.PM.getFactory(Unknown Source)
E/gdt_ad_mob( 3570): 	at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source)
E/gdt_ad_mob( 3570): 	at com.qq.e.ads.splash.SplashAD$1.run(Unknown Source)
E/gdt_ad_mob( 3570): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/gdt_ad_mob( 3570): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/gdt_ad_mob( 3570): 	at java.lang.Thread.run(Thread.java:761)
E/gdt_ad_mob( 3570): Caused by: java.lang.ClassNotFoundException: com.qq.e.comm.plugin.POFactoryImpl

**Comment by Mr-Cai** [comment]
没有啊，我这里正常的，你试试拉取仓库最新代码试试。pub.dev上没更新

sanyayaya <notifications@github.com> 于2020年6月12日周五 上午2:14写道：

**Comment by sanyayaya** [comment]
我新建了纯净项目，还是初始化失败
 Fail to init splash plugin
E/gdt_ad_mob( 3658): com.qq.e.comm.managers.plugin.c: Fail to getfactory implement instance for interface:com.qq.e.comm.pi.POFactory

**Comment by Mr-Cai** [comment]
> 我新建了纯净项目，还是初始化失败
> Fail to init splash plugin
> E/gdt_ad_mob( 3658): com.qq.e.comm.managers.plugin.c: Fail to getfactory implement instance for interface:com.qq.e.comm.pi.POFactory

你试一下pub.dev上新包 1.0.2+2， 不一定能解决

**Comment by sanyayaya** [comment]
真机测试才提示是包名不对。

**Comment by yy1300326388** [comment]
@sanyayaya 

我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
