### ISSUE TITLE
example 编译安装的 apk 广告加载不出

### ISSUE THREAD

**Issue by toure00** [Mr-Cai/tencent_ad#14]
RT，请问是广告id过期了，还是别的原因？

**Comment by toure00** [comment]
我知道什么原因了，2020年7月1日起，优量汇停止对个人开发者服务了，唉，独立开发者真难啊

**Comment by Mr-Cai** [comment]
5月份就停止了，在中国大陆是很难的

toure00 <notifications@github.com> 于2020年7月22日周三 下午12:20写道：

**Comment by Mr-Cai** [comment]
过期了吧，换成官方demo里的看看

toure00 <notifications@github.com> 于2020年7月22日周三 上午11:04写道：

**Comment by yy1300326388** [comment]
@toure00 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
