### ISSUE TITLE
Could not receive a message from the daemon.

### ISSUE THREAD

**Issue by hanxuefengshuang** [Mr-Cai/tencent_ad#17]
拉下来,运行直接报错Could not receive a message from the daemon.

**Comment by Mr-Cai** [comment]
哪来这么多bug

hanxuefengshuang <notifications@github.com> 于2020年7月28日周二 上午11:42写道：

**Comment by yy1300326388** [comment]
@hanxuefengshuang 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
