### ISSUE TITLE
iOS版本，什么时候开发呀

### ISSUE THREAD

**Issue by nnianhou-** [Mr-Cai/tencent_ad#18]
催更一下

**Comment by yy1300326388** [comment]
@nnianhou- 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
