### ISSUE TITLE
adnet-x5.aar not supported.

### ISSUE THREAD

**Issue by derekzhan** [Mr-Cai/tencent_ad#19]
运行出现如下错误，请问如何解决呢，感谢
Launching lib\main.dart on EML AL00 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tencent_ad:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :tencent_ad project caused this error: G:\code\flutter\tencent_ad\android\libs\adnet-x5.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Mr-Cai** [comment]
我有空帮你看看

chunge <notifications@github.com> 于2020年8月31日周一 下午3:54写道：

**Comment by nnianhou-** [comment]
同样的错误
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tencent_ad:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :tencent_ad project caused this error: /Users/nnianhou/Desktop/tencent_ad-master/android/libs/adnet-x5.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Mr-Cai** [comment]
我把build.gradle 里的 android studio classpath 版本改成4.0以下的就解决了，你们拉取最新代码就行了，自己的项目不用改

**Comment by Mr-Cai** [comment]
> 同样的错误
> Launching lib/main.dart on sdk gphone x86 in debug mode...
> Running Gradle task 'assembleDebug'...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':tencent_ad:bundleDebugAar'.
> 
> > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :tencent_ad project caused this error: /Users/nnianhou/Desktop/tencent_ad-master/android/libs/adnet-x5.aar
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 5s
> Exception: Gradle task assembleDebug failed with exit code 1

我把build.gradle 里的 android studio classpath 版本改成4.0以下的就解决了，你们不需要改，拉取最新代码就行了

**Comment by yy1300326388** [comment]
@derekzhan @nnianhou- 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
