### ISSUE TITLE
信息流广告无法显示

### ISSUE THREAD

**Issue by ysling** [Mr-Cai/tencent_ad#3]
`
W/System.err(30333):    ... 30 more
W/FileUtils(30333): Failed to chmod(/data/user/0/com.tencent.mm/app_tbs_64): 
android.system.ErrnoException: chmod failed: ENOENT (No such file or directory)
D/EgretLoader(30333): EgretLoader(Context context)
D/EgretLoader(30333): The context is not activity
W/ContentCatcher(30333): Failed to notify a WebView
I/调试日志(30333): NativeAD onNoAD: 错误码:6000 未知错误，详细码：102006
I/调试日志(30333): NativeAD onNoAD: 错误码:6000 未知错误，详细码：102006
I/调试日志(30333): onADTick: 4470

I/调试日志(30333): onADTick: 3969
`

**Comment by Mr-Cai** [comment]
102006:  没有匹配到合适的广告。禁止重试，否则可能触发系统策略导致流量收益下降
广告加载是有概率的，这个错误码官方给的答案是稍后重试
有时等一会就好了，链接在下方
https://developers.adnet.qq.com/backend/error_code.html

**Comment by Mr-Cai** [comment]
1.0.1修复了

**Comment by Mr-Cai** [comment]
> `
> W/System.err(30333): ... 30 more
> W/FileUtils(30333): Failed to chmod(/data/user/0/com.tencent.mm/app_tbs_64):
> android.system.ErrnoException: chmod failed: ENOENT (No such file or directory)
> D/EgretLoader(30333): EgretLoader(Context context)
> D/EgretLoader(30333): The context is not activity
> W/ContentCatcher(30333): Failed to notify a WebView
> I/调试日志(30333): NativeAD onNoAD: 错误码:6000 未知错误，详细码：102006
> I/调试日志(30333): NativeAD onNoAD: 错误码:6000 未知错误，详细码：102006
> I/调试日志(30333): onADTick: 4470
> 
> I/调试日志(30333): onADTick: 3969
> `

修复了

**Comment by yy1300326388** [comment]
@ysling 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
