### ISSUE TITLE
提示构造方法即将废弃

### ISSUE THREAD

**Issue by lovelilili** [Mr-Cai/tencent_ad#5]
```
D/EGL_emulation(28325): eglMakeCurrent: 0xdc985540: ver 2 0 (tinfo 0xc76b04f0)
E/gdt_ad_mob(28325): 此构造方法即将废弃，请在 Application 中初始化 SDK 后，使用不带 appId 的构造方法，详细请参考Demo
I/zygote  (28325): Rejecting re-init on previously-failed class java.lang.Class<com.qq.e.comm.plugin.POFactoryImpl>: java.lang.ExceptionInInitializerError: 
I/zygote  (28325): (Throwable with no stack trace)
I/zygote  (28325): 
E/gdt_ad_mob(28325): Exception while init UnifiedBannerView plugin
```

**Comment by Mr-Cai** [comment]
> ```
> D/EGL_emulation(28325): eglMakeCurrent: 0xdc985540: ver 2 0 (tinfo 0xc76b04f0)
> E/gdt_ad_mob(28325): 此构造方法即将废弃，请在 Application 中初始化 SDK 后，使用不带 appId 的构造方法，详细请参考Demo
> I/zygote  (28325): Rejecting re-init on previously-failed class java.lang.Class<com.qq.e.comm.plugin.POFactoryImpl>: java.lang.ExceptionInInitializerError: 
> I/zygote  (28325): (Throwable with no stack trace)
> I/zygote  (28325): 
> E/gdt_ad_mob(28325): Exception while init UnifiedBannerView plugin
> ```

忘记更改了，git仓库里的源码是新的，下个版本会更新掉

**Comment by lovelilili** [comment]
那我要用哪个版本？直接引用github里的可以么

**Comment by Mr-Cai** [comment]
> 那我要用哪个版本？直接引用github里的可以么

可以的，github里是没有这种报错的

**Comment by yy1300326388** [comment]
@shipinbaoku 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
