### ISSUE TITLE
gradle:4.0.0 报错

### ISSUE THREAD

**Issue by gaoyong06** [Mr-Cai/tencent_ad#9]
之前使用
com.android.tools.build:gradle:3.5.0
没有问题：

今天升级了下gradle
classpath 'com.android.tools.build:gradle:4.0.0

flutter run 的时候就一直有下面的错误

FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':tencent_ad:bundleDebugAar'.                                                            
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :tencent_ad project caused this error: /Users/user/flutter/.pub-cache/git/tencent_ad-cfb0d6539aa9d05d70f03566f81c11d5e8af19ef/android/libs/adnet-x5.aar
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 2m 20s

**Comment by Mr-Cai** [comment]
> 之前使用
> com.android.tools.build:gradle:3.5.0
> 没有问题：
> 
> 今天升级了下gradle
> classpath 'com.android.tools.build:gradle:4.0.0
> 
> flutter run 的时候就一直有下面的错误
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':tencent_ad:bundleDebugAar'.
> 
> > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :tencent_ad project caused this error: /Users/user/flutter/.pub-cache/git/tencent_ad-cfb0d6539aa9d05d70f03566f81c11d5e8af19ef/android/libs/adnet-x5.aar
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 20s

已修复

**Comment by yy1300326388** [comment]
@gaoyong06 

我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
